# Generated by Django 5.0.2 on 2024-02-23 06:19

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[blog.validators.validate_uz_phone_number]),
        ),
    ]
